version: 2

updates:
  # Maintain docker dependencies
  - package-ecosystem: "docker"
    schedule:
      interval: "monthly"
    target-branch: "iroha2-dev"
    directory: "/"

  # Maintain cargo dependencies
  - package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
    target-branch: "iroha2-dev"
    directory: "/"
