name: load-rs-ci-cd-master

on:
  push:
    branches:
      - 'master'

jobs:
  load-rs-dockerhub-master:
    runs-on: ubuntu-latest
    env:
  #    DOCKERHUB_ORG: soramitsu
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#      IMAGE_NAME: docker.soramitsu.co.jp/iroha2/iroha2-longevity-load-rs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     #   with:
     #     ref: ${{ github.ref }}
        
      # - name: Automated Version Bump
      #   id: version-bump
      #   uses: 'phips28/gh-action-bump-version@master'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Output new tag
      #   env:
      #     NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      #   run: echo "new tag $NEW_TAG"        


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1             

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
 #         registry: docker.soramitsu.co.jp
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true


      # - name: Docker meta
      #   id: meta
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: soramitsu/iroha2-longevity-load-rs
            
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soramitsu/iroha2-longevity-load-rs:master
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}

      # - name: Trigger jenkins job
      #   uses: GoldenspearLLC/build-jenkins-job@master
      #   with:
      #     jenkins-url: "https://jenkins.soramitsu.co.jp/"
      #     user: ${{ secrets.JENKINS_USER }}
      #     jenkins-token: ${{ secrets.JENKINS_TOKEN }}
      #     job-path: "job/iroha2/job/deploy/job/iroha2-stage1/"
  #        job-params: "{'targetEnvironment': 'iroha2/stage1', 'iroha2_deploy_image': 'hyperledger/iroha2', 'iroha2_deploy_version' : 'dev'}"
          # job_params: |
          #   {
          #     "param_1": "value_1",
          #     "param_2": "value_2"
          #   }


      # - name: ssh actions
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: s5.tst.iroha2.iroha.tech
      #     username: vzyabkin
      #     key: ${{ SSH_KEY }}
      #     port: 22
      #     script: |
      #       sudo su
      # #       cd /opt/iroha2_load_rs
      #         docker-compose down
      #         awk 'NR==6 {$0="    image: docker.soramitsu.co.jp/iroha2/iroha2-longevity-load-rs:0.0.5"}1' test.yaml > test.tmp && mv test.tmp test.yaml
      #         docker-compose up -d

  # ansible_execution:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout private repo
  #       uses: actions/checkout@v3
  #       with:
  #         repository: soramitsu/iroha-deploy
  #         token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
  #         path: .

  #     - name: Run ansible script
  #       run: |
  #         ansible-playbook playbooks/iroha2/test/all.yml --diff --limit tag_Name_iroha2_test_s5
  #       shell: bash

          