name: load-rs-ci-cd-master

on:
  workflow_dispatch:

jobs:
  load-rs-dockerhub-master:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1             

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
            
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: soramitsu/iroha2-longevity-load-rs:release

      - name: Synchronize with iroha2:dev repo
        run: |
          echo "response about the workflow end"
          sleep 10s

          