name: load-rs-ci:dev

on:
  workflow_dispatch:
jobs:
  load-rs-dockerhub-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: soramitsu/iroha2-longevity-load-rs:dev   
      - name: Synchronize with hyperledger/iroha2:dev repo
        run: |
          echo "response about the workflow end"
          sleep 10s
